apiVersion: v1
kind: Secret
metadata:
  name: backup
  namespace: default
type: Opaque
stringData:
  BACKUP_NAME: my-backup
  BACKUP_DRIVER: postgres # or mongodb
  BACKUP_DATABASE: db
  BACKUP_DIR: ./backups
  BACKUP_PASSWORD: supersecret123
  BACKUP_RETENTION: "7"
  CONNECTION_HOST: localhost
  CONNECTION_PORT: "5432"
  CONNECTION_USER: postgres
  CONNECTION_PASSWORD: supersecret123
  CONNECTION_AUTH_DB: admin
  WEBDAV_URL: https://webdav.example.com
  WEBDAV_USER: user
  WEBDAV_PASSWORD: supersecret123
  WEBDAV_PATH: backup/db
  PINGCHECK_URL: https://pingcheck.example.com
